### ISSUE TITLE
CRYPTO_HAVE_DHE Causes performance issue at require time

### ISSUE THREAD

**Issue by apechimp** [arekinath/node-sshpk#2]
When requiring this library, a performance hit is incurred at require time of 686.60 ms (on my machine) because the [`CRYPTO_HAVE_DHE`](https://github.com/arekinath/node-sshpk/blob/d268fc9a5442727dfb975a0c609f7419bc4d7057/lib/dhe.js#L14-L15) actually computes an elliptic curve when that file is executed. It looks like this change occurred in 3aab574be1ff311d663. It's not clear to me what scenario this addresses though.

**Comment by arekinath** [comment]
That seems to be an oversight on my part -- I wanted to check that the OpenSSL node.js was built against (in case you used a system OpenSSL rather than an integrated one) actually has EC support. However, upon reading the relevant code in node.js again, I believe that a node with the createECDH can never built against an OpenSSL that old (it will just fail to compile), so this check is unnecessary. I'll remove it.

Thanks!

**Comment by arekinath** [comment]
I've released v1.7.1 with this fix

**Comment by apechimp** [comment]
Awesome! Thanks very much for the prompt patch!
